apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: infra
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cmV0YWls      # "retail"
  RABBITMQ_DEFAULT_PASS: Y2hhbmdlbWU=  # "changeme"
