name: Terraform CI/CD

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/**'
  push:
    branches: [ main ]
    paths:
      - 'infra/**'

permissions:
  id-token: write   # for GitHub OIDC → AWS
  contents: read

concurrency:
  group: terraform-infra
  cancel-in-progress: false
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    env:
      AWS_REGION: eu-west-1
      TF_IN_AUTOMATION: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::916863632865:role/project-bedrock-github-actions
          role-session-name: bedrock-ci
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
- name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (PR)
        if: ${{ github.event_name == 'pull_request' }}
        run: terraform plan -input=false -no-color

      - name: Terraform Apply (main)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: terraform apply -input=false -auto-approve
